Update docker-openmetadata-server.yml

diff --git a/.github/workflows/docker-openmetadata-server.yml b/.github/workflows/docker-openmetadata-server.yml
--- a/.github/workflows/docker-openmetadata-server.yml
+++ b/.github/workflows/docker-openmetadata-server.yml
@@ -62,11 +62,24 @@ jobs:
     steps:
 
       - name: Fetch Release Data
+        id: attach_release
         env:
           GITHUB_TOKEN: ${{ secrets.GH_PAT }}
-        id: attach_release
         run: |
-          echo "UPLOAD_URL=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/thiagodeschamps/OpenMetadata/releases/tags/${{ inputs.DOCKER_RELEASE_TAG }}-release | jq .upload_url | tr -d '"' )" >> $GITHUB_OUTPUT
+          UPLOAD_URL=$(curl -s -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer $GITHUB_TOKEN" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/thiagodeschamps/OpenMetadata/releases/tags/${{ inputs.docker_release_tag }}-release | jq -r .upload_url)
+
+          if [ "$UPLOAD_URL" == "null" ] || [ -z "$UPLOAD_URL" ]; then
+            echo "Error: Failed to fetch upload URL. Check if the release exists for tag ${{ inputs.docker_release_tag }}."
+            exit 1
+          fi
+
+          echo "UPLOAD_URL=$UPLOAD_URL" >> $GITHUB_ENV
+          
+      - name: Debug Upload URL
+        run: echo "Upload URL: $UPLOAD_URL"
 
       - name: Download application from Artifact
         uses: actions/download-artifact@v4
